import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { ProductCard } from "@/components/catalog/ProductCard";
import { ProductGallery } from "@/components/catalog/ProductGallery";
import { ProductDetails } from "@/components/catalog/ProductDetails";
import { SelectionToggle } from "@/components/catalog/SelectionProvider";
import { getProduct, products } from "@/data/products";
import { categories } from "@/data/content";
import { createMetadata, safeJsonLd } from "@/lib/metadata";
import { siteConfig } from "@/config/site";

export function generateStaticParams() { return products.map((product) => ({ slug: product.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const product = getProduct(slug); return product ? createMetadata(product.title, product.summary, `/catalog/product/${slug}`) : {}; }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const product = getProduct(slug); if (!product) notFound(); const category = categories.find((item) => item.slug === product.direction); const related = products.filter((item) => item.subcategory === product.subcategory && item.slug !== product.slug).slice(0, 3); const gallery = product.gallery || (product.image ? [product.image] : []); const consultationHref = `/contacts?product=${encodeURIComponent(product.title)}&direction=${product.direction}#consultation`; const schema = { "@context": "https://schema.org", "@type": "Product", name: product.title, description: product.summary, ...(gallery.length ? { image: gallery.map((image) => `${siteConfig.url}${image}`) } : {}), ...(product.brand ? { brand: { "@type": "Brand", name: product.brand } } : {}), url: `${siteConfig.url}/catalog/product/${product.slug}` }; return <div className="section product-page"><div className="container"><Breadcrumbs items={[{ label: "Каталог", href: "/catalog" }, { label: category?.title || product.categoryLabel, href: category ? `/catalog/${category.slug}` : "/catalog" }, { label: product.title }]} /><div className="product-overview mt-10 grid items-start gap-10 lg:grid-cols-2" id="overview"><ProductGallery images={gallery} title={product.title} /><div className="product-intro"><p className="eyebrow">{product.categoryLabel}</p><h1 className="heading mt-4">{product.title}</h1>{product.brand && <p className="product-maker">Производитель <strong>{product.brand}</strong></p>}<p className="lede mt-6">{product.summary}</p><div className="product-supply-note"><h2>Документация и поставка</h2><p>Комплектацию, совместимость и актуальные условия поставки уточняйте у специалиста ABA Medical.</p></div><div className="product-actions"><ButtonLink href={consultationHref}>Получить консультацию</ButtonLink><ButtonLink href={`tel:${siteConfig.phoneHref}`} variant="secondary">Позвонить специалисту</ButtonLink><SelectionToggle product={product} /></div></div></div><nav className="product-section-nav" aria-label="Разделы страницы товара"><a href="#overview">Обзор</a>{product.details?.length ? <a href="#details">Характеристики</a> : null}{related.length > 0 ? <a href="#related">Похожие решения</a> : null}</nav><div id="details">{product.details?.length ? <ProductDetails product={product} /> : null}</div>{related.length > 0 && <section className="mt-20" id="related"><p className="eyebrow">Продолжить выбор</p><h2 className="mt-3 text-3xl font-bold">Похожие решения</h2><div className="catalog-product-grid mt-7">{related.map((item) => <ProductCard key={item.slug} product={item} />)}</div></section>}<div className="product-mobile-cta"><Link href={consultationHref}>Получить консультацию</Link><a href={`tel:${siteConfig.phoneHref}`}>Позвонить</a></div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(schema) }} /></div></div>; }
