import { expect, test } from "@playwright/test";
test("homepage and mobile navigation", async ({ page }) => { await page.goto("/"); await expect(page.getByRole("heading", { level: 1 })).toContainText("Медицинские решения для точной работы"); const menu = page.getByRole("button", { name: "Открыть меню" }); if (await menu.isVisible()) { await page.waitForLoadState("networkidle"); await menu.click(); await expect(page.getByRole("button", { name: "Закрыть меню" })).toBeVisible(); await expect(page.getByRole("navigation", { name: "Мобильная навигация" })).toBeVisible(); } });
test("catalog, category and product", async ({ page }) => { await page.goto("/catalog"); await expect(page.getByRole("heading", { level: 1 })).toContainText("Каталог"); await page.goto("/catalog/cardiology/interventional-surgery/coronary"); await expect(page.getByRole("heading", { level: 1 })).toContainText("Коронарные"); await expect(page.getByRole("heading", { name: "Стенты" })).toBeVisible(); await page.goto("/catalog/diabetes"); await expect(page.getByRole("heading", { level: 1 })).toContainText("диабет"); await page.goto("/catalog/product/628711016-355907973891-insulinovaya-pompa"); await expect(page.getByRole("heading", { level: 1 })).toContainText("Инсулиновая помпа"); });
test("catalog filters, comparison and contextual lead", async ({ page }) => { await page.goto("/catalog"); await page.getByRole("searchbox", { name: "Поиск по каталогу" }).fill("Инсулиновая помпа"); await expect(page.getByText("Показано 1 из 100")).toBeVisible(); await page.getByRole("checkbox", { name: "Сравнить" }).check(); await expect(page.getByRole("heading", { name: /Сравнение/ })).toBeVisible(); await page.goto("/contacts?product=Инсулиновая%20помпа&direction=diabetes#consultation"); await expect(page.getByText("Инсулиновая помпа", { exact: true })).toBeVisible(); await expect(page.getByRole("combobox", { name: "Направление" })).toContainText("Сахарный диабет"); });
test("news, contacts and consultation validation", async ({ page }) => { await page.goto("/blog"); await expect(page.getByRole("heading", { level: 1 })).toContainText("Практика, события"); await page.goto("/contacts"); await expect(page.getByRole("heading", { level: 1 })).toContainText("ABA Medical"); await page.getByRole("button", { name: "Продолжить" }).click(); await page.getByRole("button", { name: "Получить консультацию" }).click(); await expect(page.locator("input[name=name]:invalid")).toHaveCount(1); });
test("payment flow and product gallery", async ({ page }) => { await page.goto("/payment"); await expect(page.getByRole("heading", { level: 1 })).toContainText("От запроса до поставки"); await expect(page.getByText("01", { exact: true })).toHaveCount(0); await page.goto("/catalog/product/628711016-355907973891-insulinovaya-pompa"); await page.getByRole("button", { name: "Открыть изображение крупнее" }).click(); await expect(page.getByRole("dialog", { name: /Увеличенное изображение/ })).toBeVisible(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog", { name: /Увеличенное изображение/ })).toHaveCount(0); });
test("multi-product request persists and opens", async ({ page }) => { await page.goto("/catalog/product/628711016-355907973891-insulinovaya-pompa"); await page.getByRole("button", { name: "Добавить в заявку" }).first().click(); await expect(page.getByRole("button", { name: /Заявка на оборудование/ })).toBeVisible(); await page.goto("/catalog"); await expect(page.getByRole("button", { name: /Заявка на оборудование/ })).toBeVisible(); await page.getByRole("button", { name: /Заявка на оборудование/ }).click(); await expect(page.getByRole("complementary", { name: "Выбранное оборудование" })).toBeVisible(); await expect(page.getByRole("link", { name: /Отправить заявку/ })).toHaveAttribute("href", /contacts\?product=/); });
test("global product search", async ({ page }) => { await page.goto("/"); await page.getByRole("button", { name: "Поиск по каталогу" }).click(); await page.getByRole("searchbox", { name: "Глобальный поиск по каталогу" }).fill("Инсулиновая помпа"); await expect(page.getByRole("link", { name: /Инсулиновая помпа/ }).first()).toBeVisible(); });
test("legacy routes permanently redirect", async ({ request }) => { for (const path of ["/surgery", "/diabetsmellitus", "/deal", "/electrosurgery/tproduct/628587038-926775995101-energeticheskaya-platforma-valleylab-ft1"]) { const response = await request.get(path, { maxRedirects: 0 }); expect([307, 308]).toContain(response.status()); } });
